apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roze-prod
  region: us-east-1

managedNodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2