apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roze
spec:
  rules:
    - http:
        paths:
          - path: /reservation/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: reservations
                port:
                  number: 3000
          - path: /auth/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-http
                port:
                  number: 3001