{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cloud-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key-id
            namespace: default
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: default
{{- else }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cloud-secret-store
spec:
  provider:
    gcpsm:
      projectID: roze-501818
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: default
{{- end }}
