apiVersion: v1
kind: Secret

metadata:

  name: reservations-secret


type: Opaque


stringData:

  MONGODB_URI: "{{ .Values.reservations.mongodbUri }}"

  JWT_SECRET: "{{ .Values.reservations.jwtSecret }}"