global:
  # true  → secrets are fetched from Google Secret Manager (production)
  # false → secrets are fetched from values.local.yaml (local development)
  useExternalSecrets: true

auth:
  image:
    repository: us-east4-docker.pkg.dev/roze-501818/auth/production
    tag: latest

reservations:
  image:
    repository: us-east4-docker.pkg.dev/roze-501818/reservations/production
    tag: latest

payments:
  image:
    repository: us-east4-docker.pkg.dev/roze-501818/payments/production
    tag: latest

notifications:
  image:
    repository: us-east4-docker.pkg.dev/roze-501818/notifications/production
    tag: latest