apiVersion: v1
kind: Service

metadata:
  name: auth-tcp

  labels:
    app: auth-tcp

spec:

  type: ClusterIP

  selector:
    app: auth-tcp

  ports:
    - name: tcp
      protocol: TCP
      port: 3002
      targetPort: 3002