apiVersion: v1
kind: Service

metadata:
  name: auth

  labels:
    app: auth

spec:

  type: ClusterIP

  selector:
    app: auth

  ports:
    - name: tcp
      protocol: TCP
      port: 3002
      targetPort: 3002

    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001