services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    command: sh -c "while ! wget -q --spider http://auth:3001/; do echo 'Waiting for auth...'; sleep 3; done; while ! wget -q --spider http://reservations:3000/; do echo 'Waiting for reservations...'; sleep 3; done; pnpm test"
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - postgres

  reservations:
    build:
      context: ..
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: sh -c "pnpm run migration:run:reservation && pnpm run start:dev reservation"
    volumes:
      - ..:/usr/src/app
    env_file:
      - ../apps/reservation/.env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    build:
      context: ..
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm run migration:run:auth && pnpm run start:dev auth"
    volumes:
      - ..:/usr/src/app
    env_file:
      - ../apps/auth/.env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

  payments:
    build:
      context: ..
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    volumes:
      - ..:/usr/src/app
    env_file:
      - ../apps/payments/.env

  notifications:
    build:
      context: ..
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    volumes:
      - ..:/usr/src/app
    env_file:
      - ../apps/notifications/.env

  postgres:
    image: postgres:16-alpine
    container_name: e2e-postgres
    env_file:
      - ../.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s