apiVersion: v1
kind: Secret

metadata:
  name: notifications-secret


type: Opaque


stringData:

  GOOGLE_OAUTH_CLIENT_ID: "{{ .Values.notifications.googleOAuthClientId }}"

  GOOGLE_OAUTH_CLIENT_SECRET: "{{ .Values.notifications.googleOAuthClientSecret }}"

  GOOGLE_OAUTH_REFRESH_TOKEN: "{{ .Values.notifications.googleOAuthRefreshToken }}"

  SMTP_USER: "{{ .Values.notifications.smtpUser }}"