{{- if .Values.global.useExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifications-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        key: roze-google-oauth-client-id
    - secretKey: GOOGLE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: roze-google-oauth-client-secret
    - secretKey: GOOGLE_OAUTH_REFRESH_TOKEN
      remoteRef:
        key: roze-google-oauth-refresh-token
    - secretKey: SMTP_USER
      remoteRef:
        key: roze-smtp-user
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
type: Opaque
stringData:
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.notifications.googleOAuthClientId | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.notifications.googleOAuthClientSecret | quote }}
  GOOGLE_OAUTH_REFRESH_TOKEN: {{ .Values.notifications.googleOAuthRefreshToken | quote }}
  SMTP_USER: {{ .Values.notifications.smtpUser | quote }}
{{- end }}