apiVersion: v1
kind: ConfigMap

metadata:

  name: auth-config


data:

  HTTP_PORT: "3001"

  TCP_PORT: "3002"

  REDIS_HOST: redis

  REDIS_PORT: "6379"

  JWT_EXPIRATION: "3600"

  JWT_REFRESH_EXPIRATION: "2592000"