{{- if .Values.global.useExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: auth-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: l3v5h-auth-mongodb-uri
    - secretKey: JWT_SECRET
      remoteRef:
        key: l3v5h-jwt-secret
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.auth.mongodbUri | quote }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
{{- end }}