apiVersion: v1
kind: ConfigMap

metadata:

  name: reservations-config


data:

  HTTP_PORT: "3000"

  AUTH_HOST: auth

  AUTH_PORT: "3002"



  PAYMENTS_HOST: payments

  PAYMENTS_PORT: "3003"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "nestdb"
  POSTGRES_HOST: "l3v5h-postgresql"
  RABBITMQ_URI: "amqp://rabbitmq:rabbitmq@l3v5h-rabbitmq:5672"
