apiVersion: apps/v1
kind: Deployment

metadata:

  name: payments


  labels:

    app: payments


spec:

  replicas: 2


  selector:

    matchLabels:

      app: payments


  strategy:

    type: RollingUpdate


  template:

    metadata:

      labels:

        app: payments


      annotations:

        checksum/config: {{ (.Files.Get "templates/notifications/configmap.yaml") | sha256sum }}

        checksum/secret: {{ (.Files.Get "templates/notifications/secret.yaml") | sha256sum }}


    spec:


      imagePullSecrets:

        - name: gcr-json-key


      containers:


        - name: payments


          image: "{{ .Values.payments.image.repository }}:{{ .Values.payments.image.tag }}"

          imagePullPolicy: Always


          envFrom:


            - configMapRef:

                name: payments-config


            - secretRef:

                name: payments-secret