apiVersion: apps/v1
kind: Deployment

metadata:

  name: payments


  labels:

    app: payments


spec:

  replicas: 2


  selector:

    matchLabels:

      app: payments


  strategy:

    type: RollingUpdate


  template:

    metadata:

      labels:

        app: payments


      annotations:

        checksum/config: {{ (.Files.Get "templates/notifications/configmap.yaml") | sha256sum }}

        checksum/secret: {{ (.Files.Get "templates/notifications/secret.yaml") | sha256sum }}


    spec:


      imagePullSecrets:
        {{- if eq .Values.global.cloudProvider "gcp" }}
        - name: gcr-json-key
        {{- end }}


      containers:


        - name: payments


          image: "{{ .Values.payments.image.repository }}:{{ .Values.payments.image.tag }}"

          imagePullPolicy: Always


          # ШАГ 5: Внедрение секретов в микросервис.
          # Здесь Kubernetes берет манифест Secret (который мы создали на предыдущем шаге,
          # и в котором лежит ключ STRIPE_SECRET_KEY) и пробрасывает его внутрь Docker-контейнера.
          # Директива `envFrom` означает: "Возьми все ключи из этого секрета и сделай их 
          # переменными окружения (Environment Variables) операционной системы внутри пода".
          envFrom:


            - configMapRef:

                name: payments-config


            - secretRef:

                name: payments-secret