apiVersion: v1
kind: Secret

metadata:

  name: payments-secret


type: Opaque


stringData:

  MONGODB_URI: "{{ .Values.payments.mongodbUri }}"

  STRIPE_SECRET_KEY: "{{ .Values.payments.stripeSecretKey }}"

  GOOGLE_OAUTH_CLIENT_ID: "{{ .Values.payments.googleOAuthClientId }}"

  GOOGLE_OAUTH_CLIENT_SECRET: "{{ .Values.payments.googleOAuthClientSecret }}"

  GOOGLE_OAUTH_REFRESH_TOKEN: "{{ .Values.payments.googleOAuthRefreshToken }}"

  SMTP_USER: "{{ .Values.payments.smtpUser }}"