{{- if .Values.global.useExternalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payments-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: payments-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: roze-payments-mongodb-uri
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: roze-stripe-secret-key
    - secretKey: GOOGLE_OAUTH_CLIENT_ID
      remoteRef:
        key: roze-google-oauth-client-id
    - secretKey: GOOGLE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: roze-google-oauth-client-secret
    - secretKey: GOOGLE_OAUTH_REFRESH_TOKEN
      remoteRef:
        key: roze-google-oauth-refresh-token
    - secretKey: SMTP_USER
      remoteRef:
        key: roze-smtp-user
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.payments.mongodbUri | quote }}
  STRIPE_SECRET_KEY: {{ .Values.payments.stripeSecretKey | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.payments.googleOAuthClientId | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.payments.googleOAuthClientSecret | quote }}
  GOOGLE_OAUTH_REFRESH_TOKEN: {{ .Values.payments.googleOAuthRefreshToken | quote }}
  SMTP_USER: {{ .Values.payments.smtpUser | quote }}
{{- end }}