{{- if .Values.global.useExternalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloud-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret # Имя секрета, которое ждёт Bitnami Postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: l3v5h-postgres-password
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
{{- end }}
