apiVersion: v1
kind: ConfigMap

metadata:

  name: auth-config


data:

  HTTP_PORT: "3001"

  


  JWT_EXPIRATION: "3600"

  JWT_REFRESH_EXPIRATION: "2592000"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "nestdb"
  POSTGRES_HOST: "l3v5h-postgresql"
  RABBITMQ_URI: "amqp://rabbitmq:rabbitmq@l3v5h-rabbitmq:5672"
