apiVersion: v1
kind: Service

metadata:
  name: payments
  labels:
    app: payments

spec:
  type: ClusterIP

  selector:
    app: payments

  ports:
    - name: tcp
      protocol: TCP
      port: 3003
      targetPort: 3003